# Site settings
title: Janice Note
tagline: You can't go wrong with this note.
description: "This page will be making you find hype places as well as the brand in Korea easier and give some information about them."
url: "https://janicenote.com"
author:
  name: "Minji Janice Cho"
  email: "minjicho318@gmail.com"
  url: "https://janicenote.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
permalink: /:title
paginate: 8

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
Plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# 블로그 disqus shortname
disqus:
  shortname: janicenote-com
